import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import './styles/styles.css'

import { AppSidebar } from "@/components/ui/AppSidebar"
import { SidebarProvider } from "@/components/ui/SideBar"
import QueryProvider from "@/components/providers/QueryProvider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
}) 

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <QueryProvider>
          <SidebarProvider defaultOpen={true}>
            <div className="flex min-h-screen">
              <AppSidebar />
              <main className="flex-1 overflow-y-auto p-6 bg-muted h-screen">{children}</main>
            </div>
          </SidebarProvider>
        </QueryProvider>
      </body>
    </html>
  )
}
